// Roadmap data for the Vibe Coding (AI-Assisted) learning path.

export const vibeLevels = [
  {
    id: "vibe-0",
    number: 0,
    slug: "mindset-orientation",
    title: "Mindset & Orientation",
    subtitle: "Pahami dunia AI coding sebelum mulai",
    description:
      "Sebelum menyentuh tools, kamu perlu paham: apa itu vibe coding, bagaimana AI coding bekerja, apa yang realistis dan apa yang tidak. Level ini membentuk pola pikir yang benar.",
    duration: "3 hari",
    difficulty: "Pemula",
    viewers: 2841,
    lessonsCount: 4,
    miniProject: "Mapping tools & workflow pribadi",
    accent: "from-cyan-500/30 to-blue-500/10",
    tags: ["AI", "Mindset", "Workflow", "Tools"],
    lessons: [
      { slug: "apa-itu-ai-development", title: "Apa Itu AI-Assisted Development", summary: "Memahami cara kerja AI dalam membantu coding.", duration: "6 menit", viewers: 2103 },
      { slug: "perbedaan-nocode-aicode", title: "No-Code vs Low-Code vs AI Coding vs Manual", summary: "Kapan pakai yang mana.", duration: "8 menit", viewers: 1892 },
      { slug: "workflow-modern-developer", title: "Workflow Modern Developer", summary: "Alur kerja developer 2025 yang realistis.", duration: "7 menit", viewers: 1756 },
      { slug: "tools-ecosystem", title: "Tools Ecosystem Overview", summary: "Cursor, ChatGPT, Claude, Bolt, Lovable, V0, GitHub, Vercel, Supabase.", duration: "10 menit", viewers: 2045 },
    ],
  },
  {
    id: "vibe-1",
    number: 1,
    slug: "first-app",
    title: "First App Experience",
    subtitle: "Rasakan: 'Saya bisa bikin app'",
    description:
      "Install tools, tulis prompt pertama, generate landing page, edit hasilnya, dan deploy ke internet. Dalam satu level kamu sudah punya website live.",
    duration: "1 minggu",
    difficulty: "Pemula",
    viewers: 3127,
    lessonsCount: 6,
    miniProject: "Landing page sederhana (live di internet)",
    accent: "from-emerald-400/30 to-cyan-500/10",
    tags: ["Setup", "Prompt", "Deploy", "Vercel"],
    lessons: [
      { slug: "install-tools", title: "Install Tools", summary: "Setup Cursor, GitHub, dan Vercel.", duration: "10 menit", viewers: 2456 },
      { slug: "github-basics", title: "GitHub Basics", summary: "Buat repo, push, dan kolaborasi dasar.", duration: "8 menit", viewers: 1987 },
      { slug: "prompt-basics", title: "Prompt Basics", summary: "Cara menulis prompt yang menghasilkan kode bagus.", duration: "12 menit", viewers: 2234 },
      { slug: "generate-landing-page", title: "Generate Landing Page", summary: "Bikin halaman pertama pakai AI.", duration: "15 menit", viewers: 2678 },
      { slug: "edit-hasil-ai", title: "Edit Hasil AI", summary: "Cara memperbaiki dan menyesuaikan output AI.", duration: "10 menit", viewers: 1845 },
      { slug: "deploy-website", title: "Deploy Website", summary: "Publish ke internet lewat Vercel.", duration: "8 menit", viewers: 2123 },
    ],
  },
  {
    id: "vibe-2",
    number: 2,
    slug: "basic-app-building",
    title: "Basic App Building",
    subtitle: "Bangun app yang lebih dari satu halaman",
    description:
      "Pahami frontend vs backend, struktur app modern, prompting UI, dan dasar React + Next.js + Tailwind. Cukup untuk membangun portfolio website.",
    duration: "2 minggu",
    difficulty: "Pemula - Menengah",
    viewers: 2456,
    lessonsCount: 5,
    miniProject: "Portfolio website modern",
    accent: "from-cyan-400/30 to-cyan-500/10",
    tags: ["React", "Next.js", "Tailwind", "UI"],
    lessons: [
      { slug: "frontend-backend", title: "Frontend & Backend", summary: "Apa bedanya dan kapan butuh masing-masing.", duration: "8 menit", viewers: 1876 },
      { slug: "struktur-app-modern", title: "Struktur Aplikasi Modern", summary: "Folder, file, dan konvensi.", duration: "10 menit", viewers: 1654 },
      { slug: "prompting-ui", title: "Prompting UI", summary: "Cara minta AI bikin UI yang bagus.", duration: "12 menit", viewers: 1923 },
      { slug: "intro-react-nextjs", title: "Intro React & Next.js", summary: "Konsep dasar tanpa harus hafal syntax.", duration: "15 menit", viewers: 1567 },
      { slug: "tailwind-basics", title: "Tailwind Basics", summary: "Styling cepat tanpa nulis CSS manual.", duration: "10 menit", viewers: 1789 },
    ],
  },
  {
    id: "vibe-3",
    number: 3,
    slug: "vibe-ui-engineering",
    title: "Vibe UI Engineering",
    subtitle: "Bikin UI yang terlihat profesional",
    description:
      "Design taste, hierarchy, typography, modern SaaS UI, fixing ugly AI output, responsive, dan accessibility dasar. Supaya app-mu tidak terlihat 'AI-generated'.",
    duration: "2 minggu",
    difficulty: "Menengah",
    viewers: 1892,
    lessonsCount: 7,
    miniProject: "Modern SaaS dashboard",
    accent: "from-pink-400/30 to-cyan-500/10",
    tags: ["Design", "UI/UX", "Responsive", "SaaS"],
    lessons: [
      { slug: "design-taste", title: "Design Taste", summary: "Melatih mata untuk UI yang bagus.", duration: "8 menit", viewers: 1456 },
      { slug: "hierarchy-typography", title: "Hierarchy & Typography", summary: "Ukuran, weight, spacing yang benar.", duration: "10 menit", viewers: 1234 },
      { slug: "modern-saas-ui", title: "Modern SaaS UI Patterns", summary: "Pola UI yang dipakai startup.", duration: "12 menit", viewers: 1567 },
      { slug: "fixing-ugly-ai-ui", title: "Fixing Ugly AI UI", summary: "Cara memperbaiki output AI yang jelek.", duration: "15 menit", viewers: 1789 },
      { slug: "responsive-design", title: "Responsive Design", summary: "Tampil bagus di semua ukuran layar.", duration: "10 menit", viewers: 1345 },
      { slug: "accessibility-dasar", title: "Accessibility Dasar", summary: "Supaya semua orang bisa pakai app-mu.", duration: "8 menit", viewers: 1123 },
      { slug: "component-polish", title: "Component Polish", summary: "Detail kecil yang bikin UI premium.", duration: "10 menit", viewers: 1234 },
    ],
  },
  {
    id: "vibe-4",
    number: 4,
    slug: "database-backend",
    title: "Database & Backend Basics",
    subtitle: "Simpan data dan buat user login",
    description:
      "Database basics, Supabase, CRUD, authentication, dan menghubungkan frontend ke backend. Cukup untuk bikin app yang menyimpan data user.",
    duration: "2 minggu",
    difficulty: "Menengah",
    viewers: 1567,
    lessonsCount: 5,
    miniProject: "Todo app dengan login",
    accent: "from-amber-400/30 to-cyan-500/10",
    tags: ["Supabase", "Database", "Auth", "CRUD"],
    lessons: [
      { slug: "database-basics", title: "Database Basics", summary: "Apa itu database dan kapan butuh.", duration: "8 menit", viewers: 1234 },
      { slug: "supabase-setup", title: "Supabase Setup", summary: "Setup database gratis dalam 5 menit.", duration: "10 menit", viewers: 1456 },
      { slug: "crud-operations", title: "CRUD Operations", summary: "Create, Read, Update, Delete data.", duration: "15 menit", viewers: 1345 },
      { slug: "authentication", title: "Authentication", summary: "Login, register, dan session.", duration: "12 menit", viewers: 1567 },
      { slug: "frontend-connection", title: "Frontend Connection", summary: "Hubungkan React ke Supabase.", duration: "10 menit", viewers: 1234 },
    ],
  },
  {
    id: "vibe-5",
    number: 5,
    slug: "ai-debugging",
    title: "AI Debugging & Problem Solving",
    subtitle: "Jangan panik saat error muncul",
    description:
      "Membaca error, debugging dengan AI, common AI mistakes, refactoring, dan deployment debugging. Skill yang membedakan builder dari copy-paster.",
    duration: "1 minggu",
    difficulty: "Menengah",
    viewers: 1345,
    lessonsCount: 5,
    miniProject: "Fixing broken AI app",
    accent: "from-rose-400/30 to-cyan-500/10",
    tags: ["Debug", "Error", "Refactor", "Deploy"],
    lessons: [
      { slug: "membaca-error", title: "Membaca Error", summary: "Error bukan musuh, tapi petunjuk.", duration: "8 menit", viewers: 1123 },
      { slug: "debugging-dengan-ai", title: "Debugging dengan AI", summary: "Cara minta AI bantu fix bug.", duration: "12 menit", viewers: 1234 },
      { slug: "common-ai-mistakes", title: "Common AI Mistakes", summary: "Kesalahan yang sering dibuat AI.", duration: "10 menit", viewers: 1345 },
      { slug: "refactoring", title: "Refactoring", summary: "Rapikan kode tanpa mengubah fungsi.", duration: "10 menit", viewers: 1123 },
      { slug: "deployment-debugging", title: "Deployment Debugging", summary: "Kenapa jalan di lokal tapi error di production.", duration: "12 menit", viewers: 1234 },
    ],
  },
  {
    id: "vibe-6",
    number: 6,
    slug: "real-product",
    title: "Real Product Building",
    subtitle: "Bangun produk yang bisa dipakai orang",
    description:
      "Product thinking, SaaS structure, API integration, deployment workflow, dan performance basics. Dari latihan ke produk nyata.",
    duration: "3 minggu",
    difficulty: "Menengah - Lanjutan",
    viewers: 1123,
    lessonsCount: 5,
    miniProject: "Mini SaaS app",
    accent: "from-indigo-400/30 to-cyan-500/10",
    tags: ["Product", "SaaS", "API", "Performance"],
    lessons: [
      { slug: "product-thinking", title: "Product Thinking", summary: "Berpikir seperti product builder.", duration: "10 menit", viewers: 987 },
      { slug: "saas-structure", title: "SaaS Structure", summary: "Arsitektur app berbayar.", duration: "12 menit", viewers: 876 },
      { slug: "api-integration", title: "API Integration", summary: "Hubungkan app ke layanan luar.", duration: "15 menit", viewers: 1023 },
      { slug: "deployment-workflow", title: "Deployment Workflow", summary: "CI/CD sederhana untuk builder.", duration: "10 menit", viewers: 897 },
      { slug: "performance-basics", title: "Performance Basics", summary: "App cepat = user senang.", duration: "8 menit", viewers: 789 },
    ],
  },
  {
    id: "vibe-7",
    number: 7,
    slug: "ai-builder-mastery",
    title: "AI Builder Mastery",
    subtitle: "Kuasai workflow AI secara penuh",
    description:
      "Advanced prompting, multi-AI workflow, choosing the right tool, build faster patterns, dan memahami limitasi AI.",
    duration: "2 minggu",
    difficulty: "Lanjutan",
    viewers: 892,
    lessonsCount: 5,
    miniProject: "Build app dari ide sendiri",
    accent: "from-cyan-400/30 to-blue-500/10",
    tags: ["Advanced", "Multi-AI", "Speed", "Mastery"],
    lessons: [
      { slug: "advanced-prompting", title: "Advanced Prompting", summary: "Prompt yang menghasilkan kode production-ready.", duration: "12 menit", viewers: 756 },
      { slug: "multi-ai-workflow", title: "Multi AI Workflow", summary: "Kombinasi ChatGPT + Cursor + Claude.", duration: "15 menit", viewers: 823 },
      { slug: "choosing-tools", title: "Choosing the Right Tool", summary: "Kapan pakai apa.", duration: "8 menit", viewers: 678 },
      { slug: "build-faster", title: "Build Faster Patterns", summary: "Workflow yang bikin 10x lebih cepat.", duration: "10 menit", viewers: 789 },
      { slug: "ai-limitations", title: "AI Limitations", summary: "Apa yang AI tidak bisa lakukan.", duration: "8 menit", viewers: 654 },
    ],
  },
  {
    id: "vibe-8",
    number: 8,
    slug: "professional-builder",
    title: "Professional Builder",
    subtitle: "Siap freelance dan build startup MVP",
    description:
      "Clean architecture, scalability, reusable components, UI consistency, AI + human collaboration, dan simulasi klien nyata.",
    duration: "3 minggu",
    difficulty: "Lanjutan",
    viewers: 678,
    lessonsCount: 6,
    miniProject: "Production-ready app",
    accent: "from-emerald-400/30 to-cyan-400/10",
    tags: ["Production", "Architecture", "Client", "MVP"],
    lessons: [
      { slug: "clean-architecture", title: "Clean Architecture", summary: "Struktur yang tahan lama.", duration: "12 menit", viewers: 567 },
      { slug: "scalability", title: "Scalability", summary: "App yang bisa tumbuh.", duration: "10 menit", viewers: 489 },
      { slug: "reusable-components", title: "Reusable Component System", summary: "Bikin sekali, pakai berkali-kali.", duration: "12 menit", viewers: 534 },
      { slug: "ui-consistency", title: "UI Consistency", summary: "Design system sederhana.", duration: "8 menit", viewers: 456 },
      { slug: "ai-human-collab", title: "AI + Human Collaboration", summary: "Kapan AI, kapan manual.", duration: "10 menit", viewers: 523 },
      { slug: "client-simulation", title: "Real Client Simulation", summary: "Simulasi project klien nyata.", duration: "15 menit", viewers: 478 },
    ],
  },
];

export const vibeTotalLessons = vibeLevels.reduce((s, l) => s + l.lessonsCount, 0);
export const vibeTotalViewers = vibeLevels.reduce((s, l) => s + l.viewers, 0);

export function getVibeLevelBySlug(slug) {
  return vibeLevels.find((l) => l.slug === slug);
}
